### ISSUE TITLE
gulp can`t find gulp-contact-css

### ISSUE THREAD

**Issue by j69** [seokirill/PCMatreshkaDataboom#1]
when i`m run gulp from root - gulp threw error
![2015-10-02 14 34 00](https://cloud.githubusercontent.com/assets/1506433/10246629/59477ee6-6913-11e5-8d88-d14b81acf0e2.png)

**Comment by seokirill** [comment]
Did u execute 'npm install' to install all needed modules in folder node_modules?

**Comment by seokirill** [comment]
From? I'm Rus, not so good english =(

**Comment by j69** [comment]
Oh right! Thanks! it really help:)
